package azovceva.autotests.tests;

import azovceva.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("BuyBtcButton should be in MainPage")
    void generatedTest() {
        step("Open https://utorg.pro/", () -> {
            step("// todo: just add selenium action");
        });

        step("Check Button BuyBTN on the main page", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://utorg.pro/'", () ->
            open("https://utorg.pro/"));

        step("Page title should have text 'Buy Bitcoin with Credit Card or Debit Card | UTORG'", () -> {
            String expectedTitle = "Buy Bitcoin with Credit Card or Debit Card | UTORG";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://utorg.pro/'", () ->
            open("https://utorg.pro/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}